apps/courses/urls.py
from django.contrib import admin
from django.urls import path
from .views import course_list, course_add, course_detail, do_section, do_test, show_results, course_enroll

urlpatterns = [
    path('course/<pk>/', course_detail, name='course_detail'),
    path('course/<pk>/enroll/', course_enroll, name='course_enroll'),
    path('courses/add/', course_add, name='course_add'),
    path('section/<section_id>', do_section, name='do_section'),
    path('section/<section_id>/test/', do_test, name='do_test'),
    path('section/<section_id>/results/', show_results, name='show_results'),
    path('', course_list, name='index')
]

apps/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from rest_framework import routers

import courses
# from courses.views import SectionViewSet
from . import settings, views
from students.views import student_detail

from courses.viewss import classroom, students, teachers


# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'sections', SectionViewSet)

urlpatterns = [
    path('filer/', include('filer.urls')),
    path('admin/', admin.site.urls),
    # path('register/', student_views.register, name='register'),
    path('', views.index, name='index'),
    # path('api/', include(router.urls)),
    path('contact/', include('contact.urls')),
    path('courses/', include('courses.urls')),
    path('student_detail/', student_detail, name="student_detail"),
    # path('', include('cms.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('search/',  include("watson.urls", namespace="watson")),
    path('ratings/',  include('star_ratings.urls', namespace='ratings')),

]

admin.site.site_header = "EasyLearn Dashboard"
admin.site.site_title = "EasyLearn"
admin.site.index_title = "Welcome to EasyLearn"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

apps/courses/models.py
from django.db import models
from django.urls import reverse

from main import settings

from django.contrib.auth.models import AbstractUser, PermissionsMixin, AbstractBaseUser
from users.models import CustomUser


class Student(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True, related_name="students")

    def __str__(self):
        return self.user.get_full_name()


class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=200)
    file = models.ImageField(null=True, blank=False, verbose_name="image")
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, related_name="courses")
    # price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="price")

    students = models.ManyToManyField(CustomUser, related_name='students_to_courses',
                                      limit_choices_to={'is_student': True}, blank=True)

    teachers = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='teachers_to_courses', null=True, blank=True,
                                 limit_choices_to={'is_teacher': True}, on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return reverse('course_detail', args=(self.id,))

    def __str__(self):
        return self.name


class Section(models.Model):
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    title = models.CharField(max_length=100)
    number = models.IntegerField()
    video = models.FileField(upload_to='videos/', null=True, verbose_name="")

    class Meta:
        unique_together = ('course', 'number',)

    def __str__(self):
        return f"{self.title} - {self.course}"

    def get_test_url(self):
        return reverse('do_test', args=(self.id,))

    def get_absolute_url(self):
        return reverse('do_section', args=(self.id,))

    def get_next_section_url(self):
        next_section = Section.objects.get(number=self.number + 1)
        return reverse('do_section', args=(next_section.id,))


class Question(models.Model):
    section = models.ForeignKey(Section, on_delete=models.PROTECT)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    text = models.CharField(max_length=1000)
    correct = models.BooleanField()

    def __str__(self):
        return self.text


class UserAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    answer = models.ForeignKey(Answer, on_delete=models.PROTECT)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, related_name="user_answers")

    class Meta:
        unique_together = ('question', 'user',)

apps/courses/forms.py
from django import forms
from django.contrib.auth import password_validation

from .models import Course, Section
from .widgets import DropzoneFileInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.utils.translation import gettext, gettext_lazy as _

# START
from .models import Student
from users.models import CustomUser
from users.forms import CustomUserCreationForm


class StudentSignUpForm(CustomUserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control formWidth', }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control formWidth', }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta(CustomUserCreationForm.Meta):
        model = CustomUser
        fields = ["email", "password1", "password2", "first_name", "last_name"]
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-control formWidth', }),
                   # 'password1': forms.TextInput(attrs={'class': 'form-control formWidth test', }),
                   # 'password2': forms.TextInput(attrs={'class': 'form-control formWidth test', }),
                   'first_name': forms.TextInput(attrs={'class': 'form-control formWidth', }),
                   'last_name': forms.TextInput(attrs={'class': 'form-control formWidth', }),
                   }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        Student.objects.create(user=user)


class TeacherSignUpForm(CustomUserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control formWidth', }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control formWidth', }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta(CustomUserCreationForm.Meta):
        model = CustomUser
        fields = ["email", "password1", "password2", "first_name", "last_name"]
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-control formWidth', }),
                   'password1': forms.PasswordInput(attrs={'class': 'form-control formWidth', }),
                   'password2': forms.PasswordInput(attrs={'class': 'form-control formWidth', }),
                   'first_name': forms.TextInput(attrs={'class': 'form-control formWidth', }),
                   'last_name': forms.TextInput(attrs={'class': 'form-control formWidth', }),
                   }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()


# END


class VideoForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ["video"]


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'category', 'file']
        widgets = {'file': forms.FileInput(
            attrs={'style': 'display: none;', 'class': 'form-control formSpace', 'required': False, }
        )}

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div('name'),
            # Div('price'),
            Div('category'),
            Div('file', css_class="mt-5"),
        )

apps/courses/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.urls import reverse
from django.db import transaction
from django.views.generic import DetailView, ListView

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import Course, Section, UserAnswer, Question
from .forms import CourseForm
from courses.serializers import SectionSerializer


class CourseListView(ListView):
    model = Course
    queryset = Course.objects.prefetch_related('students__students_to_courses')


course_list = CourseListView.as_view()


def course_add(request):
    if request.POST:
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            new_course = form.save()
            return HttpResponseRedirect(new_course.get_absolute_url())
    else:
        form = CourseForm()
    return render(request, 'courses/course_form.html', {'form': form})


class CourseDetailView(DetailView):
    model = Course


course_detail = CourseDetailView.as_view()


def do_section(request, section_id):
    section = Section.objects.get(id=section_id)
    if request.user in section.course.students.all() or request.user is section.course.teachers:
        return render(request, 'courses/do_section.html', {'section': section})
    raise PermissionDenied


def do_test(request, section_id):
    section = Section.objects.get(id=section_id)
    if not request.user.is_authenticated or request.user not in section.course.students.all():
        raise PermissionDenied
    if request.method == 'POST':
        data = {}
        for key, value in request.POST.items():
            if key == 'csrfmiddlewaretoken':
                continue
            # {'question-1': '2'}
            question_id = key.split('-')[1]
            answer_id = request.POST.get(key)
            data[question_id] = answer_id
        perform_test(request.user, data, section)
        return redirect(reverse('show_results', args=(section_id,)))
    return render(request, 'courses/do_test.html', {'section': section})


def perform_test(user, data, section):
    with transaction.atomic():
        UserAnswer.objects.filter(user=user, question__section=section).delete()
        for question_id, answer_id in data.items():
            question = Question.objects.get(id=question_id)
            answer_id = int(answer_id)
            if answer_id not in question.answer_set.values_list('id', flat=True):
                raise SuspiciousOperation('Answer is not valid for this question')
            user_answer = UserAnswer.objects.create(user=user, question=question, answer_id=answer_id)


def calculate_score(user, section):
    questions = Question.objects.filter(section=section)
    correct_answers = UserAnswer.objects.filter(user=user, question__section=section, answer__correct=True)
    try:
        return (correct_answers.count() / questions.count()) * 100
    except ZeroDivisionError:
        return 0


def show_results(request, section_id):
    if not request.user.is_authenticated:
        raise PermissionDenied
    section = Section.objects.get(id=section_id)
    return render(request, 'courses/show_results.html', {'section': section, 'score': calculate_score(request.user,
                                                                                                      section)})


class SectionViewSet(viewsets.ModelViewSet):
    queryset = Section.objects.all()
    serializer_class = SectionSerializer

    @action(detail=True, methods=['GET', ])
    def questions(self, request, *args, **kwargs):
        section = self.get_object()
        data = []
        for question in section.question_set.all():
            question_data = {'id': question.id, 'answers': []}
            for answer in question.answer_set.all():
                answer_data = {'id': answer.id, 'text': str(answer), }
                question_data['answers'].append(answer_data)
            data.append(question_data)
        return Response(data)


def course_enroll(request, pk):
    course = Course.objects.get(pk=pk)
    if request.user in course.students.all() or request.user is course.teachers:
        message = "Sunteti deja inscris la curs!"
    else:
        course.students.add(request.user)
        message = "Ati fost inscris cu succces!"
    return render(request, "courses/course_enrolled.html", {"message": message})

apps/courses/templates/courses/course_detail.html
{% extends 'index.html' %}
{% load static thumbnail ratings %}
{% block main_content %}
    <!-- ================ start banner Area ================= -->
    <section class="banner-area">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-12 banner-right">
                    <h1 class="text-white">
                        Course Details
                    </h1>
                    <p class="mx-auto text-white  mt-20 mb-40">
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ End banner Area ================= -->

    <section class="course-details-area ">
        <div class="container">
            <div style="margin-bottom: 100px;">
                <h2>
                    {{ course.name }}
                </h2></div>
            <div class="row">
                <div class="col-lg-8 course-details-left">
                    <div class="main-image">
                        <img class="img-fluid" src="{{ course.file.url }}" alt="">
                    </div>
                    <div class="content-wrapper">
                        <h4 class="title">Course Outline</h4>
                        <div class="content">
                            <ul class="course-list">
                                {% for section in course.section_set.all %}
                                    <li class="justify-content-between d-flex">
                                        <p>{{ section.title }}</p>
                                        <a class="btn text-uppercase" href="{{ section.get_absolute_url }}">View
                                            Details</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>


                <div class="col-lg-4 right-contents">
                    <ul>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Trainer’s Name</p>
                                <span class="or">{{ course.teachers.get_full_name }}</span>
                            </a>
                        </li>
                        {#                        <li>#}
                        {#                            <a class="justify-content-between d-flex" href="#">#}
                        {#                                <p>Course Fee </p>#}
                        {#                                {% if course.price == 0 %}#}
                        {#                                    <span>Gratuit</span>#}
                        {#                                {% else %}#}
                        {#                                    <span>{{ course.price }}</span>#}
                        {#                                {% endif %}#}
                        {#                            </a>#}
                        {#                        </li>#}
                    </ul>
                    {% if user.is_teacher is False and user not in course.students.all %}
                        <a href="{% url 'course_enroll' object.pk %}" class="btn text-uppercase enroll">Enroll the
                            course</a>
                    {% else %}
                        <a href="{% url 'course_enroll' object.pk %}" class="btn text-uppercase enroll">Enrolled</a>
                    {% endif %}
                    <h4 class="title">Rating</h4>
                    <div class="content">
                        {% if user not in course.students.all %}
                            <p> You need to be enrolled as a student to vote.</p>
                            {% ratings course 20 20 True %}
                        {% else %}
                            <div class="review-top row pt-40">
                                <div class="col-lg-12">
                                    <h6 class="mb-15">Provide Your Rating</h6>
                                    {% ratings course 20 20 %}
                                </div>
                            </div>
                        {% endif %}
                        <div class="comments-area mb-30">
                            <div class="comment-list">
                                <div class="single-comment single-reviews justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb">
                                            <i class="fa fa-star checked"></i>
                                        </div>
                                        <div class="desc">
                                            <h5>Enrolled studends</h5>
                                            <ul>
                                                {% for student in course.students.all %}
                                                    <li>{{ student }}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

apps/courses/templates/courses/course_enrolled.html
{% extends 'index.html' %}
{% load static thumbnail %}
{% block main_content %}
    <!-- ================ start banner Area ================= -->
    <section class="banner-area">

    </section>
    <!-- ================ End banner Area ================= -->
    <section class="sample-text-area">
        <div class="container">
            <h1>{{ message }}</h1>
        </div>
    </section>
{% endblock %}

apps/courses/templates/courses/course_form.html
{% extends 'index.html' %}
{% load static thumbnail crispy_forms_tags %}
{% block main_content %}
    <!-- ================ start banner Area ================= -->
    <section class="banner-area">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-12 banner-right">
                    <h1 class="text-white">
                        Courses
                    </h1>
                    <p class="mx-auto text-white  mt-20 mb-40">
                        Register your course right now! <br>
                    </p>
                    <div class="link-nav">
              <span class="box">
                <a href="/">Home </a>
                <i class="lnr lnr-arrow-right"></i>
                <a href="/courses">Courses</a>
              </span>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!-- ================ End banner Area ================= -->
    <div style="margin-left: 8px;margin-right: 8px;">
        <form action=".." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            <center>
                <div class="col-3">
                    {% crispy form form.helper %}
                    <input type="submit" class="btn btn-outline-primary" value="Register your course">
                </div>
            </center>
        </form>
    </div>
{% endblock main_content %}

apps/courses/templates/courses/course_list.html
{% extends 'index.html' %}
{% load static thumbnail ratings %}
{% block main_content %}
    <!-- ================ start banner Area ================= -->
    <section class="banner-area">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-12 banner-right">
                    <h1 class="text-white">
                        Courses
                    </h1>
                    <p class="mx-auto text-white  mt-20 mb-40">
                        Your place to learn some stuff! <br>
                    </p>
                    <div class="link-nav">
              <span class="box">
                <a href="/">Home </a>
                <i class="lnr lnr-arrow-right"></i>
                <a href="/courses">Courses</a>
              </span>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center container-fluid">
                <div class="col-lg-12">
                    <h2>
                        Check what Courses <br/>
                        are Available Right Now
                    </h2>
                </div>
{#                <a href="{% url 'course_add' %}">#}
{#                    <button class="btn btn-outline-primary">Adauga curs</button>#}
{#                </a>#}
            </div>
        </div>
    </section>
    <!-- ================ End banner Area ================= -->

    <!-- ================ Start Popular Course Area ================= -->
    <section class="popular-course-area">
        <div class="container-fluid">
            <div class="owl-carousel popuar-course-carusel">
                {% for course in course_list %}
                    <div class="single-popular-course">
                        <div class="thumb">
                            {% thumbnail course.file 324x182 crop upscale as thumb %}
                            <a href="course/{{ course.id }}">
                                <img class="f-img img-fluid mx-auto" src="{{ thumb.url }}" alt=""/>
                            </a>
                        </div>
                        <div class="details matchHeight">
                            <div class="d-flex justify-content-between mb-20">
                                <p class="name">{{ course.category }}</p>
                                <p class="value">
{#                                    {% if course.price == 0.00 %}#}
{#                                        Gratuit#}
{#                                    {% elif course.price == 1 %}#}
{#                                        {{ course.price }} Leu#}
{#                                    {% else %}#}
{#                                        {{ course.price }} Lei#}
{#                                    {% endif %}#}
                                </p>
                            </div>
                            <a href="course/{{ course.id }}">
                                <h4>{{ course }}</h4>
                            </a>
                            <div class="bottom d-flex mt-15">
                                {% ratings course 20 20 True %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- ================ End Popular Course Area ================= -->

{% endblock %}

apps/courses/templates/courses/do_section.html
{% extends 'index.html' %}
{% load static thumbnail %}
{% block main_content %}
    <!-- ================ start banner Area ================= -->
    <section class="banner-area">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-12 banner-right">
                    <h1 class="text-white">
                        {{ section.number }}.{{ section.title }}
                    </h1>
                    <p class="mx-auto text-white  mt-20 mb-40">
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ End banner Area ================= -->
    <section class="sample-text-area">
        <div class="container">
            <video width="1000" controls>
                <source src="{{ section.video.url }}" type="video/mp4">
            </video>
            <a href="{{ section.get_test_url }}" class="genric-btn info circle arrow">Take the test<span class="lnr lnr-arrow-right"></span></a>
        </div>
    </section>
{% endblock %}

apps/courses/templates/courses/do_test.html
{% extends 'index.html' %}
{% load static thumbnail %}
{% block main_content %}
    <!-- ================ start banner Area ================= -->
    <section class="banner-area">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-12 banner-right">
                    <h1 class="text-white">
                        Test {{ section.title }}
                    </h1>
                    <p class="mx-auto text-white  mt-20 mb-40">
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ End banner Area ================= -->
    <section class="sample-text-area">
        <div class="container">
            <hr/>
            <form action="" method="POST">
                {% csrf_token %}
                {% for question in section.question_set.all %}
                    <p><strong>{{ question.text }}</strong></p>
                    <ul>
                        {% for answer in question.answer_set.all %}
                            <li>
                                    <input type="radio" name="question-{{ question.id }}" value="{{ answer.id }}">
                                    {{ answer }}
                            </li>
                        {% endfor %}
                    </ul>
                    <hr/>
                {% endfor %}
                <input type="submit" class="genric-btn success radius" value="Submit">
            </form>
        </div>
    </section>
{% endblock %}

apps/courses/templates/courses/show_results.html
{% extends 'index.html' %}
{% load static thumbnail %}
{% block main_content %}
    <!-- ================ start banner Area ================= -->
    <section class="banner-area">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-12 banner-right">
                    <h1 class="text-white">
                        Show results
                    </h1>
                    <p class="mx-auto text-white  mt-20 mb-40">
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ End banner Area ================= -->
    <section class="sample-text-area">
        <div class="container">
            <h1>Your results</h1>
            <p>You scored {{ score }}</p>
            <ul>
                <li><a href="{{ section.get_next_section_url }}" class="genric-btn success radius">Next section</a></li>
                <br>
                <li><a href="{{ section.get_test_url }}" class="genric-btn success radius">Try again</a></li>
            </ul>
        </div>
    </section>
{% endblock %}